In [ ]:
#Access the app at this URL:https://ml-webapp-using-streamlit-tutorial-pn-2.onrender.com/

In [2]:
import pandas as pd
import kagglehub
from sklearn.feature_selection import chi2, SelectKBest
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler
import pickle

/home/codespace/.python/current/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
path = kagglehub.dataset_download("bhumikatandon/breastcancerdata")
print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/bhumikatandon/breastcancerdata?dataset_version_number=1...

100%|██████████| 1.90k/1.90k [00:00<00:00, 2.48MB/s]

Extracting files...
Path to dataset files: /home/codespace/.cache/kagglehub/datasets/bhumikatandon/breastcancerdata/versions/1

In [4]:
total_data = pd.read_csv("/home/codespace/.cache/kagglehub/datasets/bhumikatandon/breastcancerdata/versions/1/breast-cancer.csv")

total_data.head(40)

,target,age,menopause,tumor_size,inv_nodes,node_caps,deg_malig,breast,breast_quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
5,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,left,left_low,no
6,no-recurrence-events,50-59,premeno,25-29,0-2,no,2,left,left_low,no
7,no-recurrence-events,60-69,ge40,20-24,0-2,no,1,left,left_low,no
8,no-recurrence-events,40-49,premeno,50-54,0-2,no,2,left,left_low,no
9,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,left_up,no
10,no-recurrence-events,40-49,premeno,0-4,0-2,no,3,left,central,no
11,no-recurrence-events,50-59,ge40,25-29,0-2,no,2,left,left_low,no
12,no-recurrence-events,60-69,lt40,Oct-14,0-2,no,1,left,right_up,no
13,no-recurrence-events,50-59,ge40,25-29,0-2,no,3,left,right_up,no
14,no-recurrence-events,40-49,premeno,30-34,0-2,no,3,left,left_up,no
15,no-recurrence-events,60-69,lt40,30-34,0-2,no,1,left,left_low,no
16,no-recurrence-events,40-49,premeno,15-19,0-2,no,2,left,left_low,no
17,no-recurrence-events,50-59,premeno,30-34,0-2,no,3,left,left_low,no
18,no-recurrence-events,60-69,ge40,30-34,0-2,no,3,left,left_low,no
19,no-recurrence-events,50-59,ge40,30-34,0-2,no,1,right,right_up,no
20,no-recurrence-events,50-59,ge40,40-44,0-2,no,2,left,left_low,no
21,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,left,left_low,no
22,no-recurrence-events,30-39,premeno,25-29,0-2,no,2,right,left_low,no
23,no-recurrence-events,50-59,premeno,40-44,0-2,no,2,left,left_up,no
24,no-recurrence-events,50-59,premeno,35-39,0-2,no,2,right,left_up,no
25,no-recurrence-events,40-49,premeno,25-29,0-2,no,2,left,left_up,no
26,no-recurrence-events,50-59,premeno,20-24,0-2,no,1,left,left_low,no
27,no-recurrence-events,60-69,ge40,25-29,0-2,no,3,right,left_up,no
28,no-recurrence-events,40-49,premeno,40-44,0-2,no,2,right,left_low,no
29,no-recurrence-events,60-69,ge40,30-34,0-2,no,2,left,left_low,no
30,no-recurrence-events,50-59,ge40,40-44,0-2,no,3,right,left_up,no
31,no-recurrence-events,50-59,premeno,15-19,0-2,no,2,right,left_low,no
32,no-recurrence-events,50-59,premeno,Oct-14,0-2,no,3,left,left_low,no
33,no-recurrence-events,50-59,ge40,Oct-14,0-2,no,1,right,left_up,no
34,no-recurrence-events,50-59,ge40,Oct-14,0-2,no,1,left,left_up,no
35,no-recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
36,no-recurrence-events,50-59,ge40,0-4,0-2,no,2,left,central,no
37,no-recurrence-events,50-59,ge40,15-19,0-2,no,1,right,central,no
38,no-recurrence-events,40-49,premeno,Oct-14,0-2,no,2,left,left_low,no
39,no-recurrence-events,40-49,premeno,30-34,0-2,no,1,left,left_low,no

In [5]:
total_data = total_data.drop_duplicates().reset_index(drop = True)
total_data.head(100)

,target,age,menopause,tumor_size,inv_nodes,node_caps,deg_malig,breast,breast_quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
...,...,...,...,...,...,...,...,...,...,...
95,no-recurrence-events,30-39,premeno,25-29,0-2,no,2,left,left_low,no
96,no-recurrence-events,40-49,ge40,20-24,0-2,no,3,left,left_low,no
97,no-recurrence-events,50-59,ge40,30-34,0-2,no,3,right,left_low,no
98,no-recurrence-events,50-59,premeno,25-29,0-2,no,2,right,right_low,no
99,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,right_low,no

In [6]:
total_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   target       272 non-null    object
 1   age          272 non-null    object
 2   menopause    272 non-null    object
 3   tumor_size   272 non-null    object
 4   inv_nodes    272 non-null    object
 5   node_caps    272 non-null    object
 6   deg_malig    272 non-null    int64
 7   breast       272 non-null    object
 8   breast_quad  272 non-null    object
 9   irradiat     272 non-null    object
dtypes: int64(1), object(9)
memory usage: 21.4+ KB

In [7]:
total_data["target"] = pd.factorize(total_data["target"])[0]
total_data["age"] = pd.factorize(total_data["age"])[0]
total_data["menopause"] = pd.factorize(total_data["menopause"])[0]
total_data["tumor_size"] = pd.factorize(total_data["tumor_size"])[0]
total_data["inv_nodes"] = pd.factorize(total_data["inv_nodes"])[0]
total_data["node_caps"] = pd.factorize(total_data["node_caps"])[0]
total_data["breast"] = pd.factorize(total_data["breast"])[0]
total_data["breast_quad"] = pd.factorize(total_data["breast_quad"])[0]
total_data["irradiat"] = pd.factorize(total_data["irradiat"])[0]
total_data = total_data.dropna()

In [8]:
X = total_data.drop("target", axis = 1)
y = total_data["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [9]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [10]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.7272727272727273

In [11]:
pickle.dump(model, open("Breast_Cancer_Classifier.pkl",'wb'))